"""Runtime configuration for detection, OCR, model, and simulation."""

import numpy as np

import user_config
from onceworld.paths import (
    ANCHOR_DIR as ANCHOR_DIR_PATH,
    ASSET_DIR as ASSET_DIR_PATH,
    CHECKPOINT_DIR as CHECKPOINT_DIR_PATH,
    MONSTERS_CSV,
    UNLABELED_ICON_DIR as UNLABELED_ICON_DIR_PATH,
)

ASSET_DIR = ASSET_DIR_PATH
ANCHOR_DIR = ANCHOR_DIR_PATH

ANCHOR_SCALES = np.asarray(user_config.ANCHOR_SCALES, dtype=float)
ANCHOR_THRESHOLD = float(user_config.ANCHOR_THRESHOLD)

UNIT_THRESHOLD = 0.20
UNIT_MARGIN_THRESHOLD = 0.02
UNIT_WARN_THRESHOLD = 0.35

CHECKPOINT_DIR = CHECKPOINT_DIR_PATH
CHECKPOINT_GLOB = "unit_resnet18_*.pt"

UNLABELED_ICON_DIR = UNLABELED_ICON_DIR_PATH
UNLABELED_ICON_PREFIX = "img"
UNLABELED_ICON_DIGITS = 4

BATTLE_MONSTERS_CSV = MONSTERS_CSV
BATTLE_SIM_TRIALS = 100
BATTLE_SIM_DELTA_TIME = 0.02
BATTLE_SIM_DURATION = 40.0

TESS_CONFIG_LEVEL = r"--psm 7 -c tessedit_char_whitelist=Lv.0123456789"
TESS_CONFIG_COIN = r"--psm 7 -c tessedit_char_whitelist=0123456789xX, "
